### PR TITLE
Adding collections handler

### PR DESCRIPTION
**Pull request by dmarro89**
Implemented the following HTTP endpoints for collection operations.

PART-A - Managing collections:

- GET `/collections`: List all collections (handled by HandlerGetCollections).
- GET `/collections/{collectionName}`: Get collection by name (handled by HandlerGetCollection).
- POST `/collections/{collectionName}`: Create a new collection (handled by HandlerCreateCollection).
- DELETE `/collections/{collectionName}`: Delete a collection (handled by HandlerDeleteCollection).

PART-B - Add/remove data collections:
- GET `/collections/{collectionName}/get/{key}`: Retrieve a value by key from a specified collection (handled by HandlerCollectionGetById).
- GET `/collections/{collectionName}/items`: Retrieve all collection items (paginated - pageSize and page parameters)
- POST `/collections/{collectionName}/set`: Set key-value pairs in a specified collection (handled by HandlerCollectionSet).
- DELETE `/collections/{collectionName}/delete/{key}`: Delete a key from a specified collection (handled by HandlerCollectionDelete).
- GET `/collections/{collectionName}/get/{key}`: Retrieve a specific key-value from a collection (handled by HandlerGetCollection).

### CODE REVIEW

**Comment by dmarro89** [comment]
Hi @vdmitriyev, I know that you're busy but I'm going ahead with some new developments.
Is it okay for you if I start to merge this PR and then (when you have time) you can review it and add some comments?
Thanks

**Comment by dmarro89** [comment]
Don't worry, I really appreciate your contribution.
I'll wait, no problem.
Thanks

**Comment by vdmitriyev** [comment]
@dmarro89 Hi

I started to review your updates from the perspective of an external user. Initially I wanted to use newly a create API by calling them from 3rd party tool. In this case it is a Python script I have added here: `examples/python/daredb_tester.py`. 
The tests have been divided into two parts, I have edited our initial comment to establish this parts:

* "PART-A - Managing collections"
* "PART-B - Add/remove data collections"

I could successfully test the part "PART-A", which includes management of collections.

However, I was not that successfully with the part "PART-B". Thus, I could not add/remove data from a custom collection. Here is a error I see in the Python script, which calls API:

```bash
DEBUG - Populate DB with sample data via URL (collection: sample): https://127.0.0.1:2605/collections/sample
ERROR - HTTP Code: 400; content: b'Collection "sample" already exists\n'
ERROR - HTTP Code: 404; content: b'404 page not found\n', url: https://127.0.0.1:2605/collections/sample/getAllItems
```

Do you have an idea, why the database says that the `collection` exists, but still cannot access it.

P.S. I have also added a [Taskfile](https://taskfile.dev/) to the current PR. It is just there to simplify the development workflow. See README.md for further details.

**Comment by dmarro89** [comment]
Non I'm realizing that I've not updated the PR description, sorry.
Let me update the description.
Thanks 
@vdmitriyev

**Comment by dmarro89** [comment]
If you allow, I can update the python script to test the database.
Anyway I'm developing a UI interface for the database -> Here's the repo (but I haven't commited anything yet).
@vdmitriyev

**Comment by vdmitriyev** [comment]
@dmarro89 thanks for fast response. 

Now I see that endpoints have a different names 👍 
If you would like to change the Python script, just do it 😃 Now, when it is clear, that the wrong APIs have been used, I could also adapt the script.

In parallel to `UI client`, I would suggest to create and maintain a OpenAPI yaml file as part of the main DareDB repo, so it would be easier to evolve APIs. I will create an issue and prepare a initial draft

**Comment by vdmitriyev** [comment]
@dmarro89 I have also noticed, that you have adapted a subset of the suggestions listed here - https://github.com/dmarro89/dare-db/discussions/34#discussioncomment-9829371

**Comment by dmarro89** [comment]
> #34 (comment)
Just to explain @vdmitriyev 
Actually I've "refactored" the list of commands that you've proposed but they are all implemented.
- [ ] List all collections: GET request: http://localhost:2605/collections/**list**/ -> I have removed the "list" from the path because it is redundant, the http method already explains the action we're doing -> GET /collections 
- [ ]  Create a new collection: GET request: http://localhost:2605/collections/**create**/:collection -> I have removed the "create" from the path because it is redundant, the http method already explains the action we're doing -> POST /collections/{collectionName}
- [ ]  Get size of a collection: GET request: http://localhost:2605/collections/size/:collection -> I have merged this with the endpoints that returns all the items. you can get the size simply getting the length of the array returned.
- [ ]  Iterate of a collection: GET request: http://localhost:2605/collections/iterate/:collection?page=1&pagesize=1000
page: current page with keys -> -> I have merged this with the endpoints that returns all the items
- [ ]  Delete collection: DELETE request: http://localhost:2605/collections/delete/:collection -> I have removed the "delete" from the path because it is redundant, the http method already explains the action we're doing -> DELETE /collections/{collectionName}

**Comment by vdmitriyev** [comment]
@dmarro89 thanks for fixing the Python script. Have also answered your commend on API design here - https://github.com/dmarro89/dare-db/discussions/34#discussioncomment-10995856

**Comment by vdmitriyev** [comment]
As long as an API design will be finalized, the PR can be accepted and merged

**Pull request merged**
